libr/asm/arch/blackfin/bfin-dis.c
I believe making the disassembly lowercase is necessary for anal plugins.
=> Made disassembly lowercase

libr/debug/p/debug_unicorn.c
=> uc_hook_add fixed

examples/my-cpu/Makefile
Installing should now work correctly
=> Fixed my-cpu Makefile to not assume dylib

libr/bin/format/pyc/pyc.h
=> format/pyc/pyc.h: include r_lib.h

yara/yara2/Makefile.acr, yara/yara3/Makefile.acr
Now they properly install to home or global with r2pm
=> Fixed Makefile.acr files for yara2 and yara3

dwarf/Makefile, dwarf/main.c
NOT FOR MERGE:
There are currently 2 methods implemented (C-like output and pf output) in the code. Need to pick one and build on top of it.
Also I will remove strng struct and instead use r_str_buf before final commit, but currently I am not focusing on fixing that and instead working on the main part. Also code has real bad error handling which needs to be fixed (with return value and default value in case something fails).
For struct :
```
struct abc {
int a;
char b;
int c;
char *d;
int e; 
int f;
};
```
pf output:
```
pf.abc ic...i:pii a b c d e f
```
and C output:
```
struct abc {
int a;
char b;
ut16 temp0[1];
ut8 temp1[1];
int c;
ut32 temp2[1];
char *d;
int e;
int f;
};
```
=> Initial commit for dwarf

zpu/Makefile, zpu/README.md, zpu/zpu.c
For now only supports dissassembly
=> initial implementation for ZPU plugin

baleful/anal/anal_baleful.c
=> fix in esil expresion for ROL and ROR

libr/Makefile, libr/asm/Makefile, libr/asm/p/x86_tab.mk
Fix the tab package to make installable via r2pm
ref: radare/radare2#660
=> Add tab to r2pm

.travis.yml
=> Add install test for x86tab

Makefile.acr, libr/bin/p/mdmp.mk
Renamed dlang to bin in the Makefile.acr, not sure if this change will be accepted but it makes more sense to me.
Fixed errors in the mdmp.mk file which was causing failures.
=> Minor Makefile changes

bcl/core_bcl.c, dwarf/Makefile, dwarf/main.c
Need some review in checking if this compiles.
Usage:
```
?:dwarf init file_to_read_dwarf_info_from
?:dwarf structname [addr_if_required]
```
=> Dwarf reloaded

dwarf/main.c
`?:dwarfj structname` to output in json format (works after doing `?:dwarf init filename` )
=> deallocate dwarf types and json format output

dwarf/main.c
Print specific members from structure using abc.def format and get address for writing specific field in struct
Code contains my trail to get iddi, idda working instead of using ?:dwarf but it is not implemented properly yet.
=> More on dwarf

dwarf/main.c
```
iddi absolute_filepath
idd structname    // print struct
idda structname.member1.submemberx.... // print address where the value is
iddv structname.member1.submemberx.... // print value
```
Pointers are also accessed using `.` itself instead of `->` (C-like way)
=> follow pointer and add support for idd* subcommands

dwarf/Readme.md, dwarf/main.c
Updated Readme too.
Can be merged!! :)
=> add iddlf, iddlg and iddd

libr/bin/format/mdmp/pe/pe.c, libr/bin/format/mdmp/pe/pe.h, libr/bin/format/mdmp/pe/pe_specs.h
Brings in the new PE headers from the core.
Maybe one day we will be in the core and these minor PRs will not be needed, wink wink, nudge nudge :p
=> MDMP - Support for breaking changes in the core (r2 1.3.0)

libr/asm/p/Makefile, libr/bin/format/pyc/marshal.c, libr/bin/format/pyc/marshal.h, libr/bin/format/pyc/pyc.c, libr/bin/format/pyc/pyc.h, libr/bin/p/bin_pyc.c
This code is still raw. I will fix it gradually
=> Adding more pyc objects

libr/asm/arch/pyc/opcode.h, libr/asm/arch/pyc/pyc_dis.h, libr/asm/arch/pyc/pyc_disasm.c, libr/asm/p/Makefile, libr/asm/p/asm_pyc.c, libr/asm/p/pyc.mk, libr/bin/format/pyc/marshal.c, libr/bin/format/pyc/marshal.h, libr/bin/format/pyc/pyc.c, libr/bin/format/pyc/pyc.h, libr/bin/p/bin_pyc.c
I forgot to add new files in previous pull request.
=> Add new files

pimp/LICENSE, pimp/README.md, pimp/pimp.py, pimp/pimp_wrapper.py
Triton based concolic execution plugin.
=> add pimp plugin

dwarf/Readme.md, dwarf/main.c
json support for iddd command
@jpenalbae would you please review this in your free time? :smile:
=> re-write dwarf plugin with added support for better array output and

dwarf/main.c
Fixed previous pr (temporary fix in get_num_from_attr) and add other details for help in scripting.
=> fix get_num_from_attr, add help, improve json output, fix type output

libr/bin/format/pcap/pcap.c, libr/bin/format/pcap/pcap.h, libr/bin/p/bin_pcap.c
=> Add IPv6 support to pcap plugin

.travis.yml
Just testing a theory that spawned from the issues with getting the MDMP PR to test correctly.
=> travis: actually test the pull requests

libr/bin/format/mdmp/pe/pe.c, libr/bin/format/mdmp/pe/pe.h
Does what it says in the title
=> MDMP: Bump the pe headers to match core

Makefile.acr, libr/anal/p/Makefile, libr/anal/p/anal_evm.c, libr/anal/p/evm.mk, libr/debug/p/debug_evm.c, libr/io/p/io_evm.c
Came up with some EVM improvements here.
=> Evm improvements

r2snowman/Makefile
I hope this is an acceptable way.
=> Fix cloning to non-empty existing directory (#139)

libr/anal/p/x86_udis.mk
Fixes https://github.com/radare/radare2-extras/issues/153.
=> x86_udis.mk: also pass LDFLAGS

libr/anal/p/anal_atombios.c, libr/asm/arch/atombios/atombios.c, libr/asm/arch/atombios/atombios.h, libr/bin/p/bin_atombios.c
- Include local data blocks as locs
- Autodetect binary fix
- Include global data blocks as sections
- Add ESIL to resolve data from tables
- Bugfix ESIL for various instructions
- Bugfix ESIL for jmp conditions
- Easier to read disasm, still with ESIL support
- TODO: IO via ESIL
=> atombios: Improvements

.travis.yml, dwarf/main.c, libr/asm/Makefile, yara/yara/core_yara.c
=> travis: Fix Install rust as default, use gcc-7, 14.04, install make && omit [BR] tests

.travis.yml, libr/asm/p/asm_mc6809.c
=> mc6809: update to match new RasmOp API

baleful/anal/anal_baleful.c
I hope I find some time later to make this a bit more beautiful, but it should do the job now, as a hotfix
=> refix bale anal-plugin (use the new interrupt api)

libr/anal/p/evm.mk, libr/asm/arch/evm/evm.c, libr/asm/p/asm_blackfin.c, libr/asm/p/asm_m68k_net.c, libr/asm/p/asm_msil.c, libr/asm/p/asm_psosvm.c, libr/asm/p/asm_x86_bea.c
Work in progress.
There is at least one more case that I have not covered.
I've limited this PR to fix the problems when building the plugins. I will try to address other things in a separate PR.
=> Fix compilation

libr/debug/p/debug_unicorn.c
r2pm install unicorn now works.
debugging with unicorn is still broken. seems unrelated to RIOMap, but I'm not sure.
```
$ r2 -version
radare2 3.5.1 21780 @ linux-x86-64 git.3.5.1
commit: 4ec482ba2d4f554beeafb3aa47758e970bcab937 build: 2019-05-23__12:31:06
$ r2pm install unicorn
Already up to date.
DEPENDS: unicorn-lib
Wed May 22 10:34:28 EDT 2019
Install Done For unicorn
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/home/user/.local/share/radare2/prefix'
checking for c compiler... gcc
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
checking for libewf ... no
checking pkg-config flags for …
```
=> Switching from RIOSection to RIOMap in unicorn debug

.gitignore, libr/bin/format/pyc/marshal.c, libr/bin/p/bin_pyc.c, libr/bin/p/pyc.mk
- Update struct and/or methods
- Disable TYPE_LONG that depends on libgmp
=> Various fix to make pyc bin plugin compile

libr/bin/p/bin_pyc.c
- Update to more recent core def and struct
- Fix byte code version detection
- Add base adress information
=> Fix and update for pyc bin plugin

yara/yara/core_yara.c
Add option to yara plugin allowing to print offsets and strings of matches.
**Test plan**
```bash
r2 bins/elf/vim
[0x00055a40]> yara scanS
BLOWFISH_Constants
0x002960c0: $c1 : a6 0b 31 d1 
0x002960c4: $c3 : ac b5 df 98 
0x002960c8: $c5 : db 72 fd 2f 
0x002960cc: $c7 : b7 df 1a d0 
0x002964c0: $c9 : e9 70 7a 4b 
0x002968c8: $c11 : 1c 26 4c f6 
SHA256_Constants
0x001936c4: $c1 : 98 2f 8a 42 
0x0019372b: $c3 : 91 44 37 71 
0x0019379d: $c5 : cf fb c0 b5 
0x001937e5: $c7 : a5 db b5 e9 
```
=> Add print string option to yara

.travis.yml
Replace radare-regression by radare2/test to use the new test location. Add test for yara in radre2.
=> Update test folder to radare2/test and add test for yara in Travis

yara/yara/core_yara.c
Yara API has [changed](https://github.com/VirusTotal/yara/commit/0a49ac72f1d35f28ffff4c2851208380c2da86fa)
**Test plan**
Previous test should pass
=> Update yara  module according to yara API changes

libr/anal/p/Makefile, libr/anal/p/anal_pyc.c, libr/anal/p/pyc.mk
* Fix build script.
* Set default anal type to `R_ANAL_OP_TYPE_ILL`.
=> Fix build script of pyc anal plugin

yara/yara/core_yara.c
yara API has changed with 4.0.0 version (#238). Previous versions of yara are supported with the changes.
=> Support yara versions less than 4.0.0

.travis.yml
=> Update travis to remove pyc

r2taint/readme.md, r2taint/taint.py
It is an attempt to create static data flow tracking using esil emulation engine.
...
**Test plan**
Just run via `#!pipe /path/to/taint.py -h`
...
...
=> Static taint analysis

yara/yara/core_yara.c
Set flag space and flags for yara hits to keep track of yara results.
**Test plan**
Test have been updated: [17392](https://github.com/radareorg/radare2/pull/17392)
=> Set flags for yara hits

.github/workflows/ci.yml
- Test for ARM Vector35
- Test for Motorola 6809
- Test for X86 Udis86 Disassembler
**Test plan**
Tests are run in CI.
=> Add tests in ci.yml

.github/workflows/ci.yml
Thanks to https://github.com/radareorg/radare2-pm/commit/c0de19caff81d154a2ad8c7548bf4594f4a18b70 the problem with building yara in CI is solved.
**Test plan**
Yara is tested in CI.
#276
=> Add yara build and test in CI.

.github/workflows/ci.yml
Keystone tests are run each time in CI.
=> Add keystone tests in CI

yara/yara/core_yara.c
The yara scan results are mapped to the correct virtual address when it is possible
**Test plan**
Test have been updated: https://github.com/radareorg/radare2/pull/18643
=> Map yara scan results to correct virtual address

libr/asm/arch/swf/swfdis.c, libr/asm/arch/swf/swfdis.h, libr/asm/p/asm_swf.c
=> Fix #286 - Fix the bad code in swf disassembler

.github/workflows/ci.yml
Add r2svd build in CI workflow.
**Test plan**
No test so far, it will be added later.
None
=> Add r2svd build in CI.

libr/anal/p/anal_nios.c, libr/asm/arch/spc700/spc700dis.c, libr/asm/p/asm_m68k_net.c, libr/asm/p/asm_mc6809.c, yara/yara/core_yara.c
**Checklist**
Modifications introduce by https://github.com/radareorg/radare2/pull/19596
=> Replace sdb_fmt by r_strf

.github/workflows/ci.yml
**Checklist**
Add evm build in CI.
=> Add evm compilation in CI.

libr/anal/p/anal_x86_udis.c, libr/asm/p/asm_x86_udis.c
**Checklist**
Correct x86udis build.
=> Correct x86udis build

.github/workflows/ci.yml
**Checklist**
Until finding why it does not pass in CI but it pass locally.
=> Temporary disable yara in CI

.github/workflows/ci.yml
Add asahi build in CI
**Checklist**
=> Update ci.yml with asahi plugin

x86iced/Cargo.lock, x86iced/Cargo.toml, x86iced/src/lib.rs, x86iced/src/r2api_ext.rs
=> X86iced features

.github/workflows/ci.yml
**Checklist**
Enable CI for vc4 plugin.
=> Enable CI for vc4 plugin

.github/workflows/ci.yml
Brings back the VC4 test in CI.
**Checklist**
=> Update ci.yml with VC4 test

Makefile.acr, afen/Makefile, afen/README.md, afen/meson.build, afen/src/main.c
**Checklist**
Adds an `afen` plugin that allows a user to rename expressions inside r2.
=> Add afen plugin

.github/workflows/ci.yml
Add r2afen build in CI.
**Checklist**
=> Update ci.yml with afen plugin

afen/README.md, afen/src/main.c
=> Make afen function specific

r2angr/r2angr
=> Use TMPDIR env or fallback to /tmp for temporary log file

r2ida/README.md, r2ida/r2ida/r2ida.py
=> r2ida IDA plugin

r2svd/Makefile, r2svd/r2svd.py
**Checklist**
Updates from `pkg_resources` (setuptools) to `importlib` and updates to version-1.0 of cmsis-svd, good refactor carried on by [ARMify project](https://nlnet.nl/project/ARMify/).
The use of my fork is temporary, hopefully https://github.com/cmsis-svd/cmsis-svd/pull/185 gets reviewed and [fixed](https://github.com/cmsis-svd/cmsis-svd/pull/185#issuecomment-2375592693) upstream by @VincentDary.
=> R2svd no setuptools

r2angr/angr, r2angr/r2angr
Affected packages: unicorn, pypcode
**Checklist**
=> r2angr: fix latest cmake issues on termux

r2svd/Makefile
**Checklist**
Update build process to prefer uv pip if available.
=> Change to prioritize using uv
