- libr/bin/format/mdmp/mdmp.c
- libr/bin/format/mdmp/mdmp_specs.h
- libr/bin/p/bin_mdmp.c
This PR fixes Minidump sections, module structs need to be packed otherwise compiler would insert padding and it wouldn't match file image.
Now module names (full file path) are stored but need proper UTF-16 parsing. Also fixed few other mistakes, I guess I was drunk when I wrote that as it could never have worked and didn't made any sense :D
now it looks like this
```
[0x00000000]> ia
[..]
[Sections]
idx=01 vaddr=0x77950000 paddr=0x00000fb8 sz=1572864 vsz=1572864 perm=----- name=C:_Windows_SysWOW64_ntdll.dll
idx=02 vaddr=0x75370000 paddr=0x00001024 sz=1114112 vsz=1114112 perm=----- name=C:_Windows_SysWOW64_kernel32.dll
[..]
```
Note that paddr doesn't actually point to code section but only to MINIDUMP_MODULE struct, it's all still very incomplete and sections are kinda abused here with …
> Fix Minidump sections

- libr/asm/p/asm_x86_tab.c
Copied over commented out source from refactor. This is the complete tab.
> Remove comments from tab instructions

- keystone/Makefile
- keystone/build.mk
> fix keystone build

- Makefile.acr
This fixes obsolete yara2/yara3 references failing the build via `make`.
> fix obsolete yara2/3 reference in Makefile.acr

- r2snowman/r2snow
Sometimes r2snow returns proper r2 commands but still exits with non-0 return value causing r_sys_cmd_str_full: failed command 'r2snow'.
This dirty hack supresses this.
> Make r2snow always exit with 0

- r2snowman/r2snow.pl
The rf function reads a file into an array context; however it is
assigned to the scalar $source below. On some (all?) versions of perl,
this scalar is then assigned the line count of the source file. Joining
the array solves this problem.
> r2snow.pl: Fix reading source file into scalar

- .travis.yml
The r2snow test fails with the following message: 
ERROR: Build failed. You probably need 'brew install cartr/qt4/qt' and 'brew install boost' or 'sudo apt-get install libboost-dev libqt4-dev'
Adding these should make the build succeed again.
> Fix Travis checks: r2snow dependencies

- r2snowman/Makefile
Fixes a regression caused by merging #87 before
https://github.com/yegord/snowman/pull/104
Once that is merged, this commit should be reverted.
> Use snowman fork fabianfreyer/snowman for now

- libr/bin/format/mdmp/mdmp.c
- libr/bin/format/mdmp/mdmp_pe.c
- libr/bin/format/mdmp/pe/pe.c
- libr/bin/format/mdmp/pe/pe.h
- libr/bin/format/mdmp/pe/pe_specs.h
- libr/bin/p/bin_mdmp.c
The MDMP plugin will no longer segfault in the latest git build of r2.
Support for the haddr changes in the core have been added.
I don't know if you will want to merge this as it will no longer work with current release builds (I think). Or does r2pm have a way of versioning?
I know that MDMP is not yet feature complete due to lack of ability to integrate bin plugins with the r2 debugger and I do not have the time to submit a proposal and then code it!  But could we migrate MDMP into the core to prevent these sort of pe dependency regressions or is there a sneaky way that MDMP can access the PE bin headers?
Note: I will submit new regression tests to cater for the haddr ASAP.
> MDMP - Applied fixes due to changes in the core

- .travis.yml
- dwarf/Makefile
- dwarf/Readme.md
- dwarf/main.c
With this patch,
`r2pm -i dwarf-parser` seems to work on properly (travis is green).
Fix infinite loop `idddl` command for pointers to struct/union.
Refactor r_cmd_dwarf_call function.
> add iddt command, fix makefile and proper integration with travis

- .travis.yml
This should make travis use r2-extras with applied commits of PR instead of using master.
Need review in this line specifically: https://github.com/radare/radare2-extras/compare/master...P4N74:travis-fix?expand=1#diff-354f30a63fb0907d4ad57269548329e3R39
> r2pm to use local r2-extras cloned repo instead of master in travis

- rust-asm6502/src/lib.rs
This PR fixes a segfault due to changes in the RAsmPlugin structure.
I could be interesting to add plugins templates in this repository to ease creating new Rust plugins.
> [rust-asm6502] Support the new plugin API

- libr/bin/format/mdmp/pe/pe.c
- libr/bin/format/mdmp/pe/pe.h
- libr/bin/p/bin_mdmp.c
This just brings MDMP inline with the new RBinPlugin API changes and updates the PE files to prevent segfaults.
Regression tests now fail only on the info field, I will update this and submit a PR.
> MDMP - Support for the next round of breaking changes in the core

- libr/bin/Makefile
- libr/bin/format/pcap/pcap.c
- libr/bin/format/pcap/pcap.h
- libr/bin/p/Makefile
- libr/bin/p/bin_pcap.c
- libr/bin/p/pcap.mk
WIP
A few questions -
1) How should a bin plugin export `pf` expressions? Should I do this using sdb?
2) @XVilka , is this something like what you were looking for in [#3574](https://github.com/radare/radare2/issues/3574)? 
3) As @radare commented in the issue, I feel that it would be simpler to use gdbserver's `--remote-debug` option to log packets for replaying, compared to a pcap.
> Initial pcap plugin

- .travis.yml
- libr/bin/format/mdmp/pe/pe.c
- libr/bin/format/mdmp/pe/pe.h
- libr/bin/format/mdmp/pe/pe_specs.h
- libr/bin/p/bin_mdmp.c
1. This brings the PE headers in line with r2 v1.7.
2. This fixes a horrible typo that has prevented the regression tests from running.
As a result the regression tests for mdmp do not pass at this moment in time.
First thing to check are the regression tests now running. Next is to work out what has broken the tests.
> MDMP - r2 v1.7 Compatability

- libr/bin/p/bin_mdmp.c
Added useful variables from the MDMP header into the binary infos
section.
We now show the Flags and Streams in `iI`
```
[0x004014e0]> iI
arch     x86
binsz    6646738
+bintype  mdmp
bits     64
canary   false
crypto   false
endian   little
+flags    0x00040802
havecode true
hdr.csum 0x00000000
linenum  false
lsyms    false
machine  AMD64
maxopsz  16
minopsz  1
nx       false
os       Windows NT Workstation 6.1.7601
pcalign  0
pic      false
relocs   false
rpath    NONE
static   false
+streams  14
stripped false
va       true
```
> mdmp: Added custom binary info

- r2wars/README.md
I'm pretty sure the README meant the Core War game. `codewars` OTOH is a programming challenge website.
> r2wars: fix the misspelled name of the original game

- libr/asm/Makefile
- libr/asm/arch/include/dis-asm.h
- libr/asm/arch/include/elf/nios.h
- libr/asm/arch/include/mybfd.h
- libr/asm/arch/include/safe-ctype.h
- libr/asm/arch/include/xregex.h
- libr/asm/arch/include/xregex2.h
- libr/asm/arch/nios/gnu/cgen-asm.c
- libr/asm/arch/nios/gnu/cgen-bitset.c
- libr/asm/arch/nios/gnu/cgen-dis.c
- libr/asm/arch/nios/gnu/cgen-opc.c
- libr/asm/arch/nios/gnu/cpu-nios.c
- libr/asm/arch/nios/gnu/nios-asm.c
- libr/asm/arch/nios/gnu/nios-desc.c
- libr/asm/arch/nios/gnu/nios-desc.h
- libr/asm/arch/nios/gnu/nios-dis.c
- libr/asm/arch/nios/gnu/nios-ibld.c
- libr/asm/arch/nios/gnu/nios-opc.c
- libr/asm/arch/nios/gnu/nios-opc.h
- libr/asm/arch/nios/gnu/safe-ctype.c
- libr/asm/p/Makefile
- libr/asm/p/asm_nios.c
- libr/asm/p/nios.mk
Hello,
Here is my disassembler plugin targetting the Altera Nios embedded soft processor. It is based on GNUPro Nios CDK 3.1 from https://sourceforge.net/projects/cdk4nios/ and supports nios16 and nios32 machs. Many changes from modern binutils were manually merged in to assist with targetting modern compilers.
Tested with nios32 test file: http://www.jk1mly.org/electoronics/nios/tcsc/NioSyst/cpu_sdk/src/hello_world.out
Compared with original objdump: http://www.jk1mly.org/electoronics/nios/tcsc/NioSyst/cpu_sdk/src/hello_world.objdump
Edit: Forgot about r2pm, so I will work on that now.
> Altera Nios disassembler plugin

- libr/Makefile
Forgot to update a Makefile needed for r2pm.
> nios: Update libr/Makefile for r2pm plugin use.

- libr/asm/arch/evm/evm.c
- libr/asm/arch/evm/evm.h
```
0x0000007d      65627a7a7230.  push6 0x627a7a723058
0x00000084      20             sha3
0x00000085      19             not
0x00000086      19             invalid
0x00000087      40             blockhash
0x00000088      40             invalid
0x00000089      6626e7d13b32.  push7 0x26e7d13b32b77d
0x00000091      99             swap10
0x00000092      648519bde7b1   push5 0x8519bde7b1
```
> Fixes long push operands display

- libr/asm/arch/evm/evm.c
Fixes #194 
```
┌ (fcn) fcn.00000000 14
│   fcn.00000000 ();
│           0x00000000      6080           push1 0x80
│           0x00000002      6040           push1 0x40
│           0x00000004      52             mstore
│           0x00000005      6004           push1 0x04
│           0x00000007      36             calldatasize
│           0x00000008      10             lt
│           0x00000009      610195         push2 0x0195
│           0x0000000c      57             jumpi
└           0x0000000d      63ffffffff     push4 0xffffffff
0x00000012      7c0100000000.  push29 0x0100000000000000000000
0x00000030      6000           push1 0x00
0x00000032      35             calldataload
0x00000033      04             div
0x00000034      16             and
0x00000035      6305514a3e     push4 …
```
> fixes trimmed last bytes in disassembly

- libr/asm/arch/include/mybfd.h
https://github.com/radare/radare2/blob/master/libr/asm/arch/include/mybfd.h#L584-L585
Fixes building `vc4`, and possibly others
> Update <mybfd.h> to reflect the static inlining of bfd_get_bits

- libr/asm/arch/pyc/pyc_disasm.c
- libr/bin/format/pyc/marshal.c
I found two very subtle bugs in the pyc bin and asm module.The first one is a very obvious heap overflow (initial size is 0) and the second one is a single NULL byte overflow.
> fix overflow bugs in pyc module

- libr/bin/format/pyc/marshal.c
- libr/bin/format/pyc/pyc.c
- libr/bin/format/pyc/pyc.h
- libr/bin/p/bin_pyc.c
- Correct pointer offset after finding entry point
- Define the right size for Python object type
- Prevent memory corruption problem when naming section
...
**Test plan**
```
$> cat fhello.py
def hello():
print("hello world!\n")
hello()
$> python2.7 -m py_compile fhello.py
$> rabin2 -S fhello.pyc 
[Sections]
nth paddr       size vaddr       vsize perm name
――――――――――――――――――――――――――――――――――――――――――――――――
0   0x0000001e  0x14 0x0000001e   0x14 ---- module
1   0x0000004d   0x9 0x0000004d    0x9 ---- module_.hello
```
...
closes #225 
...
> Fix #225 - Python pyc fix for section detection 

- libr/anal/Makefile
- libr/anal/p/anal_pyc.c
- libr/anal/p/pyc.mk
- libr/asm/arch/pyc/opcode.c
- libr/asm/arch/pyc/opcode.h
- libr/asm/arch/pyc/opcode_anal.c
- libr/asm/p/pyc.mk
- libr/bin/format/pyc/marshal.c
- libr/bin/format/pyc/marshal.h
- libr/bin/format/pyc/pyc.c
- libr/bin/format/pyc/pyc.h
- libr/bin/p/bin_pyc.c
* Basic analysis of python bytecode
* Give out jump info of `HASJABS` and `HASJREL` opcode
* CALL_* opcodes need support of stack emulation of stack across basic blocks
* Some opcodes have to be `R_ANAL_OP_TYPE_UNK` since python virtual machine is fully "stack-based"
**Concerned issue**
https://github.com/radareorg/radare2/issues/4228
> .pyc anal plugin

- .travis.yml
- libr/Makefile
- libr/anal/Makefile
- libr/anal/p/Makefile
- libr/anal/p/anal_ba2.c
- libr/anal/p/ba2.mk
- libr/asm/Makefile
- libr/asm/arch/ba2/ba2_disas.c
- libr/asm/p/Makefile
- libr/asm/p/asm_ba2.c
- libr/asm/p/ba2.mk
Adding support for NXP Beyond Architecture 2 CPU disassembly and analysis. (Used for example in JN5169 ZigBee CPU).
...
**Test plan**
I opened a few .elf files for this CPU.
...
**Related PRs**
Also needs radare2-pm PR #105 and radare2 PR #17063 (this one because NXP uses a non-standard EM_ constant in the elf file header).
> Adding support for BA2 CPU

- libr/bin/format/pcap/pcap.c
- libr/bin/format/pcap/pcap.h
- libr/bin/p/bin_pcap.c
- types/include/pcap.h
Fix pcap plugin to make it work again. Previously, it looks for RBinObject in `arch->o` which is not initialized to assign `bin_obj` to `arch->o->bin_obj` and it should use the `void **bin_obj` parameter in `load_buffer` instead. Therefore, it always `return false` and prevents the plugin from parsing the file.
```
static bool load(RBinFile *arch) {	
if (!arch || !arch->o) {	
return false;	
}
```
Besides, I rewrite most parts to use `r_read_*` and `r_buf_read_*` to ensure endianness is correct and store the results in its `bin_obj` `pcap_obj_t` so I could use it later for testing remote debugging radareorg/ideas#60.
**Test plan**
1. Install the plugin. `r2pm install pcap`
2. Open a .pcap file `r2 test/bins/pcap/sample0.pcap`
3. List symbols `is` and compare them …
> Fix and refactor pcap r_bin plugin

- libr/asm/arch/swf/swfdis.c
patch for "https://github.com/radareorg/radare2-extras/issues/254"
**Test plan**
...
...
> patch Heap overflow

- libr/asm/arch/blackfin/bfin-asm.c
- libr/asm/arch/blackfin/bfin-dis.c
- libr/asm/p/asm_blackfin.c
Radare2-extras currently provides only disassembly for the Blackfin architecture. This change adds a new feature, namely Blackfin assembly. This is implemented in the new file bfin-asm.c, with integration changes made to file asm_blackfin.c. 
Also included as a separate commit are some changes to the file that implements the Blackfin disassembly (bfin-dis.c), which include a number of minor bug fixes, as well as the cosmetic change of removing the output of comments showing decimal translations of immediate values. 
The Blackfin assembly supports all instructions in the official programmers guide from Analog Devices (https://www.analog.com/media/en/dsp-documentation/processor-manuals/Blackfin_pgr_rev2.2.pdf), including support for parallel instructions. 
I added a …
> Blackfin assembly capability added

- .github/workflows/ci.yml
- libr/anal/p/anal_atombios.c
- libr/asm/arch/atombios/atombios.c
- libr/asm/arch/atombios/atombios.h
- libr/asm/p/asm_atombios.c
- libr/asm/p/atombios.mk
- libr/bin/format/atombios/atombios.h
- libr/bin/p/bin_atombios.c
This makes atombios asm/anal/bin plugins all work again.  Previously they would not compile.
> atombios: Make plugins compile again && GitHub CI

- .travis.yml
- libr/Makefile
- libr/anal/Makefile
- libr/anal/p/Makefile
- libr/anal/p/anal_nios.c
- libr/anal/p/nios.mk
- libr/asm/arch/nios/gnu/nios-dis.c
- libr/asm/arch/nios/gnu/nios-opc.c
This pull request adds rudimentary analysis support for nios target. The plugin supports both 16 and 32-bit implementations. Note that instructions size is always 16-bit and toggling between 16 and 32-bit changes the size for data and addresses along with a few key instruction differences.
**Test plan**
Nios binaries appear to be very rare but the following one may be used for testing:
elf32-nios test file: http://www.jk1mly.org/electoronics/nios/tcsc/NioSyst/cpu_sdk/src/hello_world.out
objdump: http://www.jk1mly.org/electoronics/nios/tcsc/NioSyst/cpu_sdk/src/hello_world.objdump
```
r2 -a nios -b 32 hello_world.out
```
> Update nios target

- Makefile.acr
- libr/anal/p/anal_arm_v35.c
- libr/asm/arch/arm/v35arm64/deps.mk
- libr/asm/p/asm_arm_v35.c
Build Vector35 ARM64 plugin correctly and disassembly works.
**Test plan**
No test yet but planned. First, tests have to be brought back to the CI.
> Fix Vector35 ARM64 plugin build

- baleful/anal/anal_baleful.c
[#18144](https://github.com/radareorg/radare2/pull/18144) changed functions for interrupts. This commit fixes that for baleful plugin.
**Test plan**
No test
> Fix baleful plugin build

- .github/workflows/ci.yml
#268 has removed tests of plugins and yara build in the CI. This commit bring back the tests but yara is not built yet in CI.
**Test plan**
Test are checked during CI.
> Bring back tests in CI for plugins

- libr/anal/p/anal_arm_v35.c
- libr/asm/arch/arm/v35arm64/Makefile
Add code for capstone arm64 plugin to vector35 plugin by converting fields where necessary and other minor changes. Mostly things map well from one to the other. 
**Test plan**
I will eventually try to get the whole arm64 test suite working, and also add tests for new instructions that weren't covered previously.
> Translate arm64 analysis to v35 disassembler

- r2snowman/Makefile
**Checklist**
- [ X ] Mark this if you consider it ready to merge
Qt4 is out of date and several system repositories do not still include it. Snowman obviously hasn't been modified in a while, but have at least Qt5. Snowman builds just fine with Qt5 with a CMake flag.
https://github.com/fabianfreyer/snowman/blob/master/doc/build.asciidoc
> extras build for snowman to use QT5

- bcl/anal_bcl.c
- bcl/bin_bcl.c
- libr/anal/p/anal_atombios.c
- libr/bin/p/bin_atombios.c
- libr/bin/p/bin_pcap.c
**Checklist**
`check_buffer` now takes two arguments as input.
> Correct check_buffer for bcl, atombios and pcap.

- libr/arch/hexagon/Makefile
Without it, older GCC would complain about relocations and shared objects.
> added -fPIC to hexagon makefile. Kindof a kludge, but it works

- libr/asm/p/arch_blackfin.c
**Checklist**
Fix compilation errors of the blackfin plugin due to `RArchPlugin` structure modifications (radareorg/radare2@97a7b7b4a3e7a1a8fc77b0cb62f6c2f9838b889b).
I have tested the installation with r2pm but I haven't checked that the plugin is working.
> Fix blackfin plugin compilation

- r2iced/src/lib.rs
- r2iced/src/r2api_ext.rs
**Checklist**
Support more x86 dialect
> r2iced: support AT&T, masm syntax

- .github/dependabot.yml
- x86iced/Cargo.toml
- x86iced/src/lib.rs
- Enable Dependabot so we get automatic PRs for iced-x86 updates
- Add Cargo metadata (disable publish, MIT license, description)
**Checklist**
> x86iced: add metadata

- Makefile.acr
**Checklist**
I forgot to check if it installs as well as to add the building and installing command to the `Makefile.acr`. Right now I tested it and the plugin can be installed, sorry for my laziness 😅
> Fix to make afen installable

- afen/README.md
- afen/src/main.c
> Fix rparse to rcore binding for afen

- r2angr/angr
- r2angr/r2angr
**Checklist**
[ In code ? (Yes) ]
Installation on termux.
NOTE: Most compatible with Python 3.11.
> Fix setup on termux

- r2svd/Makefile
**Checklist**
The upstream cmsis-svd repo has updated to version 1.0 since https://github.com/cmsis-svd/cmsis-svd/pull/185
> Repoint cmsis-svd repo to upstream cmsis-svd org
